
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - NODE_ENV=production yarn build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./dist s3://sites.lvh.me/react3.sites.lvh.me-test/ 
artifacts:
  files:
    - '**/*'
  base-directory: dist
